<?php

namespace MatchBundle\Entity;

/**
 * VersusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersusRepository extends \Doctrine\ORM\EntityRepository
{
}
